---
apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:MZjSws7jxm5fwDkQJAt9LGWjs7qc2rnFL7NVtdoczlTPXplaJ/sJwrq4jTk=,iv:Cf+8DV0yX58HUjnkEEMCjzoDCZzX7Iheb3R5wPa2/WI=,tag:Brj0r6NpkMZ2uI/tbtx3LQ==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:cW8KG4+uL+BTHPDBGM6/,iv:czQ755ooOU54RkV0+cQyXhyttTnJBpxkv8LxKfIxT70=,tag:B5dcdKjR/590m8rdJdQ8cg==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:5zu8,iv:avzfyTf37y35Si3p2uXq6Ew7DZGXJZSvQ9eZsNVbVnI=,tag:YZbtbz6i3iG55DwuLB7x7w==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:OaORIB4GRgKcYJVUOlRXinzWxg==,iv:1gLPr7+gqs1sIjJXsotE3Qu1NgB8jTZOxsgj5070okc=,tag:ctMnMCcp66bjG0UoaXSHfw==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:nooc+pOm,iv:f9xMN+/EbpEtCCR9vHPTvQP3Ppoma1HqeChjDJ2btCY=,tag:9/AaBx4IT5NZN+0f1Unq2w==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:uMTsWue8pE/Bg1AIkzZrNL7s2LKUxcapI8CJd51XlbyKQykT,iv:qhvdj2Fz+bdpIQzSpewA08ipb2TQT3OrKbivOgBb+Dc=,tag:/XHVwLhKnI+xARPkEdHq5w==,type:str]
  SMTP_TLS: ENC[AES256_GCM,data:hfeiQw+zePs=,iv:QNzVez1vF0aA9wyaevwUDtho7QpCadgUy10Fm0f7o9g=,tag:BktwGOOIe+ePgIy5S1dUDw==,type:str]
  STATIC_API_KEY: ENC[AES256_GCM,data:pYbT5pziRBTDlVULM3ZpB0jllZk+OpmSAfC0x+HhsRHPzeRha8x8iig283wwStBlNcP6addBuTV3PaSgIZOw2g==,iv:nRHOalBTtMOhfcVl6wlEAvZ9ZKArgJgp7cNZE6UJ1tA=,tag:YIv5hmvgVXTkYxk/RV+waQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZEo4UFFGeVdrbWtuenFN
        bDA2ZmhFWElMMUdINnVpNUpua3dZQlNWbTI4CllZeC9TOFNiTmJpbk92VU5URldD
        eURMaUYyMURVT3IxTldzZDV0TEVKZXcKLS0tIFJVT1ZiK0ZCQWNYTjZWYTh6UjB2
        b3VYNXphc2V2dWxjTU9sU2FUUWN0d0UKmgMYTHsA/AxVGvfsRiQ0XFT8bIS3/x4C
        z9hnAlCMjbGNlzYuXsmTDHhlrsMPiH703xJuuLKa5MJTMbyt1MXfdA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-24T21:43:39Z"
  mac: ENC[AES256_GCM,data:k8iwzn2jPWzBLa2b/m53l6TDFJTMBmkqMoXu4DXCIWCtUebJy0jrmWGf4lzhm4DYy9XG98Rh8U0vKVwqnfFCKuKFDh9Uq+YxuVGSgs0OxR0O2B2KKyziajOc27sKh0lkxRiTh+Y6NskBTM+fyeMT/0VPkRu3rwn4o2WFLdae8e4=,iv:87q8Ujs7QITpzKnuzfPWwcuEiCN7ThYvCEBaNkMzTUQ=,tag:dgbDLyFRgAwkJxFpNSOnZg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
