---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-key
type: Opaque
stringData:
  #ENC[AES256_GCM,data:7CMziU0OPe7F7kaMaPxman3QU0jSOGzsnJKNO0V1JHjXkO7oYwWJEuY5vg47eHtISM2RAuz9uemGXQ==,iv:j6Mxu99MCHwEncrnqdPrTlV/aYNU2SqwyaUilFHAE5E=,tag:IdgZgDZcruyA+vr9z54K8A==,type:comment]
  #ENC[AES256_GCM,data:uk7+m6OBMaCHlcAmYQCdbitdK7CvlydGaoMYY/jzgWLHITOMaqFIuPwKOiKBgxOmvcwRQ4ueXpDowcihgYgVdIMlw3db7Dxz/DZDyA==,iv:mWu88GCM15lLII0y+4WnusXiNgoyno0LQZbFeeIv8ZA=,tag:6Byzas1GVhD3nQ6k1HZ7lQ==,type:comment]
  #ENC[AES256_GCM,data:OdHiN/Vj2JRHHNNq24JruVPdajbz7QQPvlHDReJeKpzdgmpKnHNw0mupBX7n9HrtKfyCp5Csm3YPR0w+2vfQ1Zt1I2zIyB5j7Osn,iv:wzbbNV41ISenew1DCVAegmcuql9i9iuJoShXQuObAo0=,tag:Z5TbVdGd1inVOdVujCE1Fg==,type:comment]
  #ENC[AES256_GCM,data:aEowXNtfse8WMLhKZFbHnrw7+U5mZV9/YHTPeynxgw6mrgbSxLR576Tg5i9XrYQCr5bJnmZ3NdKKDa4ivGNMDli867UG+lYR5vmU3Js=,iv:OyjinYAOI201OWx9sqSmZJZ1zR6VYAeuXX+FWOXYbCg=,tag:ijXwFTHjU8kOnYB4BhFk8A==,type:comment]
  BOUNCER_KEY_envoy: ENC[AES256_GCM,data:crmgWPLwFYXDy+jxnRgH2kSee6EuE0/AnQHh+V3oqv6Ioqk5zAidLVnE6SUXtlUoZWifOh0Qn4SbLIrpR1uugg==,iv:umY3m6HbHlxmbj/ZMx0UgSqgHncwMTtmwP+PnfAgQDo=,tag:sPi9Bo4mVr9huvD6yiA8Qw==,type:str]
  ENVOY_BOUNCER_BOUNCER_APIKEY: ENC[AES256_GCM,data:eyYVsAHOBYvLWyehxSuUobob3b/XXArunQoJwdEJua98nlMHDBbpwwmVDBGSnyG4KJYKkRAj6oJk+psmVoUnUg==,iv:yqNWBSzUFbbVYZh2XjjNKb1GQqU+50W+rPW24WMdeso=,tag:Hmjk/VkxOA5XGX+GQH2T1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSytMM3FYWExIQzFEK2Zy
        TGlwMVBMR3pRemZZM2hKOU9IajhXZTRFT0hBCm5NTkJ4TVVQcWpuL25Ibm5jMmt4
        cWx6UXVIeWNmcTlBRUxlcWZtVU5sSkUKLS0tIEdlQjFwTC9pbjBjQVdSOHErc0Jt
        RWRuWFVPTVlEK2c4S29NVXhSTnpKTTAKJVRzYhZzhD8IGYQ4mHFiY1sybOJbLIAZ
        xmvNx9T4ohukdLOr9dJJ1IsCk2BpgJM7Qxfg60AWEQKZ2Cjuacmzsg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-24T23:13:35Z"
  mac: ENC[AES256_GCM,data:UE6y4t8Ch6m9zk5KWj/k+zTZ5I4HvVZ5ewmnZngidUwrE3e4L9SYbWHvDMYMGrvhM4VTSZslFsBtLdRmQ53VG22R4uma7u0Y0uZSYAUfn7B64Y+cUTdOugJJLQNbrFy7WzdTXzjmS0iLBomL43NlIV1sbdDs1UcGDJa+s3OmlO0=,iv:2j0njmYPVw3wXbtHIy7LPWhXOhUA8v2ZG7nLeQkEgWE=,tag:UMjXtdoMScIU4kiE/E9CaQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
