---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:/154Dic=,iv:tytv+bGIPO1FjcCB2BWM6K+Wjfz/pxAW/mGBE7IgkTc=,tag:wyxXHz54r9kfqh/xEMrUEw==,type:str]
  admin-password: ENC[AES256_GCM,data:iGHggGKw2oSArllILi0e1OF8dqA+7+afySV6+eePKwc=,iv:U+PIL8qRs55no2qmwdrj7/evi9oUwKrvFtqa4Z83/8E=,tag:/5ziB5vVVXGnK2XwO6toBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTHhpMDNJbTlwSVZGTWJ0
        K3VOTmdROXhTYVNESlo1SVFwQmg4a1ZjL1RBCjk2blVDcFRpaytFeG5RVm8ySkFy
        VjFrY1pOY0hQY0o3Sm50bzlGUWIyckkKLS0tIC9EbHRpZ2V3L29rRlJsbWJyM0RP
        VjFRRFJ1elk3U3pSZFRRWVRhdkRsSEEKXY5ek7txQDQ435238f/jD11j3hHPvp6U
        xfbp9cCir7jNx1K8A9rqxT+PuNkCebsyrmIbTFA/hOskKDrlC69LbA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-24T20:45:42Z"
  mac: ENC[AES256_GCM,data:Y5Z6CP9BKd9b2z8e1Ung74/FibkxnJZrHZWDIbTsaN19QrOKxNjZUsJNwy5ezlB4zeRDHRH1UVrq7GpphL5D9T7FDFQR8sQY/IU6BlTf5n04NtRqvfn1t4CMSg3IbBsOdtxcRoel7zprcXPsJw8+o2FKqUjaSDEXdZJcFCC2Pa0=,iv:tHjhll+vB/o46Cfs3TmY5/dhhglcfrN02cRghLLpewI=,tag:RvX+foZT4FGBK86D50UR4g==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
