---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rtabby
spec:
  interval: 1h
  path: ./kubernetes/apps/tabby/rtabby/app
  postBuild:
    substitute:
      APP: rtabby
      VOLSYNC_CLAIM: rtabby-data
      VOLSYNC_SCHEDULE: "30 5 * * *"
      VOLSYNC_CACHE_CAPACITY: 1Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: tabby
  wait: false
