---
apiVersion: v1
kind: Secret
metadata:
  name: swisstransfer-secret
stringData:
  #ENC[AES256_GCM,data:R6L2XQuyRwn2ighCYAaeIa4T4svmEP5EbJ7qdWdCnUY6zX0Mk7Jx7TstCBb6o/rqNSZAWG0mfJO1vMBQquMp8Ho5OU9YHHez,iv:7qJXMkik4qrMUodqBzCpmxpnADHhf5nCKj7pzh0KGwo=,tag:Y7goDKoeKptk07vdvyjNng==,type:comment]
  #
  #ENC[AES256_GCM,data:Z8CAhbnFvQFzUpxidhtR2DyQL7ITzYUQcuvm0pO26D/aV3pjZdtWCHq85uGUy/zIC+IzzCuoa2kkRm/tc4ViITJfXtnvtZU=,iv:EEOKyf/49kwH2D7RF1UmlA1T2+eAlysfep87bveGzWI=,tag:eCNLmozWdwaB8UV830hjFw==,type:comment]
  #ENC[AES256_GCM,data:ot4zrU//rCNviPCLGbq3Wuh8iOX+U3xJbV2WiJ7fp0c+En5wEsYC8gNakRVvoS58MaL3KPv2x55qWrU8+s3foewJD9pq6B+M,iv:9EujtR94rBcwip3JQ/McSJRyTZETanZhZW/4t92kAR4=,tag:9KP+mDnxlNcbzBnCLK3TOA==,type:comment]
  #ENC[AES256_GCM,data:IhFKUjh6Fs8JVls6YOH2ilinSqpvP1CUi148ttq8sDzuPLXYpxOSvxw=,iv:2H2PR8gMRHnTMIXngLoMYLENajOULZ9936Ixp2eF7qg=,tag:a+Y/ep6+jrrg7v1FxNhPLw==,type:comment]
  #
  #ENC[AES256_GCM,data:3fbARuurS2ybRY/JSlGXZC9tza7jrId7ElY+UVVzU8tTKK14uLNOVbbZOMlWqUWkZYo0bMGaCxQfvn7pddsD6OyXqp3ZmjCS8+L+YQ==,iv:6zb4ntKJ4pTGAfV8l1kzWWlLl7Kh0tP1GUfLcazlK9c=,tag:0eozT/zgHrTVrLxn8GnvMg==,type:comment]
  #ENC[AES256_GCM,data:n/ucft2xryi5ej7WpTg+m+Bx6Uh02C+jDBnRV3woTLHF779jJi9m2+GxkqCttu71ZB8nv984ZJc8ucFuXIa4yFbhxTvPuHNJwdkNRg==,iv:CZofYHkgtRKsLv5Aa9geMnWSjdvE4F1/el664E4MODg=,tag:WX9H5C6YgYbJ98bZUzYAmg==,type:comment]
  #ENC[AES256_GCM,data:hogSbKX/fhf1gromkF1MNWi3c+Bt8eU8eDov/Q==,iv:wtlsdlaPn3hwH0X+7PjCXGCawaZIVfztlOnAhgtQIk8=,tag:TqSwB5zSFSwJ7HO4ZzZTTg==,type:comment]
  #
  #ENC[AES256_GCM,data:A6w0Yv1NggeiFfegGUBC2R/gPmV8rwW8tQGg/vpwizWFldd2aNRuDhoJjGaqEqFfA89efgosYAvblN4iEf+jitVoG8BN,iv:4KcUsno39OybSuogG9OOlqUzzoCWNTo9CiwYWo1swc0=,tag:xRLwB+Eu74AZ9p1mezQMRA==,type:comment]
  SWISSTRANSFER_LINK: ENC[AES256_GCM,data:W96AtWuNEDTeMp3+7H4yaAT6lOf/Xls+AcCG81LC36yoPY9o1LNTXH60yMyAXvViysUBDGmCKLycA5g26vjyfjxRkamZ,iv:rqPFMa+7cDIFtN54tCLqSvYuZmAvgyaJJqMLqszvXvU=,tag:vf2OhVnQxqG82OOL3vsX/Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQTFENm03VzZwQ21mNHBH
        UGw5U3dEeE9nb25wdDZjVzh2TDRWNTJGS1JNCmpWWEhMd2ovWEN3Y08yeUxpVURU
        OFN3V2EzZ0dzYXo1dndsd3hNSldldWMKLS0tIEVXNGZWaFF1NHJRUWRMY2RyMGpT
        NERmWTBCYUdyRDY0djJ3UmY3Q2NDNDAKSFOnWji4P/jLdMtQc07GFV2axLhc/5S/
        zeZeRmSoQXHH5xDfWioivJTBLt/UgC7Vh/oKe6egsYTmo4V33pYuag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T17:23:32Z"
  mac: ENC[AES256_GCM,data:pKPzH3HUhzHF/R94xjOpdKgwDT1AY91QEpFOVWweTsFSE9n2u4REeVm5c1pZeg/6/9vvbH7YAI3JcXGuaYvZPm3Z1Nl0EcVy/3huyKZ9NxccIfYQeQWGIr5sI4qoKEpK1M1LO2nzOJWoOHOa6VsWYuplpfRtJObLNpzwNBaRPX0=,iv:CGUQf0uUnUUc+pQVZ+XiPbJCyjLvVn7RdY1XzLtXeZA=,tag:Jx4zEhMHA2GFEWPAh9WVPg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
