---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: affine

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./affine-db/ks.yaml
  - ./affine/ks.yaml
