apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:BrUdtZF8t+AXnk8UP/McENYaEc988yX/yCE0+6TZ5hM7vi3cfIo6LCRyA3G3dPgBRVRydbs=,iv:2pqRROg1dqrZMQ60IMRC9J0xn0Kiqxp4mfzU/GReO3w=,tag:8SKXoiXCCoClMDK299KylA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWFpBSTlLNEhxT0RoTjUy
        N3BnN0F5YXhQcmEvdDU1dnpqZk8yU1FZa3pZCmlFU2JlVkVjWUVOc04zS3hFOUoz
        em1kNTFkdUhoZnZxNWRlRlJrRU50T1EKLS0tIFJmOVFvdnhoSkRDNXc3OFZRQW1T
        OVJ2T3BncUFrNW9uNEY5YjdYNUI0aG8KW7JiSJB8fwlVGmwk9HZg9pFjhTIcRtta
        sts+or4ACX7fJbmM+ivKMS9BMZIQr/Jj4D7GQaQmgM6f/YwnIeN82Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T09:39:52Z"
  mac: ENC[AES256_GCM,data:nFP7P74J3XQLs1NRUX5RQ1j9et90CTNEFAk0mjl4nnClO8yfzGmb6wUiOQHUPh1FFY/Gq/zaXiTc4929lCMgc5qv0HwHyOCcFEh7fxvgrk6Fu+nAfkvMt3hNcBnDC3r5wRBftqZTfjcf6VOjYAKPz3r3VIkdChaEzxaXmjjcI5A=,iv:NhxMC+XbbPqyYenhcC58WqwQY0C7yYIu2eQmiF8X44g=,tag:sqZJbCDS1gNVWfMro34quw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
