---
apiVersion: v1
kind: Secret
metadata:
  name: samba-secret
stringData:
  ACCOUNT_mc: ENC[AES256_GCM,data:Tyn2PFgk+qHTHglB8SoDTDrPnaiJLh8Qzkkb1A==,iv:sFT0eK9HHzp9Tf3kkVVPUTySvVVQ3AgIzJWBGi2FitM=,tag:EwF3DDnSTLhUPhSTTz8DLA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VDlpOTFkandqVjZjRzhz
        MHdDa0U1SnptY0dUalJQSUlRSndHUFB2d1NVClJZYVlSWlhyRFA5UEJEVkd3b1F5
        S2ZERVBJZ2lvQ2VqTm1OK3Uyc2JtOUEKLS0tIGppcVI0MDdsZEVpZHg0cmlQWlRU
        cnN1ajlzQU85Y2QwaDdxMi9Db3RLMWsKOetlvkyjeQ3TQlqoCYXCpdDJA6GZERTf
        lOyxmVy82Vrdt/3ntLYa0VJ7EPdCRNbtQt9oRR1ifjOXvnrtaCgIoQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T18:23:28Z"
  mac: ENC[AES256_GCM,data:lzabQTTWbCSaDj6TJY94mavAg+9Jz8ftYHur3uQ68p4TUPgVS/DBRRUTbI0/ttc91Jj+Q95wrSBTphLJN2rNl8o5WT5hZ/8Z6E+gJRfFgWBBu57XyCYvHdiim1aWimP+GCyxi7ALtYoPWddAySvlOjxIMio6Zp1BI3/Q3o5WBK0=,iv:eWTxwRUnSwwIME6BA+yZ+/eE1FuAiftay+3LNjJfCLU=,tag:do2ZSV1mYemjzBl5p2dkgQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
