apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:mkGF45mnYYk=,iv:SjUu5fddZbIs5QFspAdeGfX3Ky54Tv7tSiXHN6m6h3o=,tag:RxsEGFCikO1JewkGaqU1Kg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYld0TFZGZTNOK1IvWWd1
        YTluVkg0UHJXV2lZQ1FxZTBXZzN4STM3OW4wCnBYMytoa2NJZ1hDaGdRNGhiV3pS
        ZGdwL0JINVlJa1p4dTgxbXk4SHppb3MKLS0tIFcwM3hORkFWOENXditMM0F1VjJD
        c2pralNTQW9mL09hSzdPQzhrZWtjTjAKJW2WWWD0CGUot+j8JtFoc3nPeOcDD5ma
        1WR9/ZxPI9xet4eFBkRFFBAY+AD0aD/DXUFIVidyIyKkPECCX1b4gA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T09:39:52Z"
  mac: ENC[AES256_GCM,data:BZ2QNkQuNKIoNPFQgSGMWftBJG9SG3MLyhLVM6YzC6hI/GyqV2pv4oGmjHq8HJhZcm+PqMzZvEtLXK3EllZ7qSRp5lzniVGqIYH3E1E6RhkZjqP7jxe0Baf2IbbR5WDvBOG8KMpLSLkPqdxQlqCPFck1ZNYBlA3ZXm+nkMHvcEg=,iv:r1VGKMUN8yKcko4ap+EdqwqKvxexrUrgBiMm+t7pSgc=,tag:rUVOix0wf2fy2aypkN37cA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
