---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:mkGF45mnYYk=,iv:SjUu5fddZbIs5QFspAdeGfX3Ky54Tv7tSiXHN6m6h3o=,tag:RxsEGFCikO1JewkGaqU1Kg==,type:str]
  VOLSYNC_S3_ENDPOINT: ENC[AES256_GCM,data:Hd48VCM478AZhhj6eZZBiM23YVQu/RE=,iv:BxTNEox9sumQHY7vdQXWiYmDse4XwA+CawGmUmgxW/c=,tag:xzc4nJEghEWj8t8G2CerGQ==,type:str]
  VOLSYNC_BUCKET: ENC[AES256_GCM,data:dz4nw65f7QveoOn05ag=,iv:0MxDZ//1Haeyvat4KBir66g9+xpaQrdX968arhkc1dg=,tag:FsmGOwxrVO9mp7B2QNfAyA==,type:str]
  VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:NHWWv88VJnz08/vnQtoeba1kB0FGHob4BDRH5iQk1aTRqYlvex0qljcnk1Y=,iv:hRR/eIb7wXZQlgj6w1cN3hNOy0MDidyoYBYSBX3ooZs=,tag:354PUmoT8874MMCKkda8bQ==,type:str]
  VOLSYNC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xG1Hw//CmgWYmkmHWjGBxYYm9Is=,iv:nIxewUWZaSV4adZhrlKu5p1aawXWtukCIjaehb58MLQ=,tag:ZxTuYarqwIm2FCBiVVi+GA==,type:str]
  VOLSYNC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:du/SU304g/tGguKZvJjazt3YehGrMo+Im8DFWBumWa+1HJGjuCdmGg==,iv:8frVXiIS1wz3HzgfTQP7tc19firs3DDYksn8F8D7NYM=,tag:uOeEyTz9KOX1vcUYE6Yu7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYld0TFZGZTNOK1IvWWd1
        YTluVkg0UHJXV2lZQ1FxZTBXZzN4STM3OW4wCnBYMytoa2NJZ1hDaGdRNGhiV3pS
        ZGdwL0JINVlJa1p4dTgxbXk4SHppb3MKLS0tIFcwM3hORkFWOENXditMM0F1VjJD
        c2pralNTQW9mL09hSzdPQzhrZWtjTjAKJW2WWWD0CGUot+j8JtFoc3nPeOcDD5ma
        1WR9/ZxPI9xet4eFBkRFFBAY+AD0aD/DXUFIVidyIyKkPECCX1b4gA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T17:45:05Z"
  mac: ENC[AES256_GCM,data:JQzD8sni0DEWAf7pkchdqcm30XxjVBFsTXVaHfdJpKMfcq3HN705dDJ3m9w3qq4i4HpsZSqnKq0jIDUYo3MLSh2RksoU01W1L9+lRfulwIZ4oyULcolxFJuJGQ3FavfwbDH3kEh4/kRaa88a3i/eIMfU/hIZvppO94r672qEhIg=,iv:XJPbOEuabDpD0yHdoI1VHCeuvaz5RUnYqY7BxKip3yY=,tag:Ajtx2rXWHRByHzJX4RirHQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
