---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:mkGF45mnYYk=,iv:SjUu5fddZbIs5QFspAdeGfX3Ky54Tv7tSiXHN6m6h3o=,tag:RxsEGFCikO1JewkGaqU1Kg==,type:str]
  VOLSYNC_S3_ENDPOINT: ENC[AES256_GCM,data:cffYSyg7ecwS8253SNgYFbm6QYmqoV90StM=,iv:MTvq1TWv8zUzuud/kOsH+3vrnqaWkywVBWSw7MzPOIc=,tag:upmmRKZDfCwT3gfyl60tIw==,type:str]
  VOLSYNC_BUCKET: ENC[AES256_GCM,data:dz4nw65f7QveoOn05ag=,iv:0MxDZ//1Haeyvat4KBir66g9+xpaQrdX968arhkc1dg=,tag:FsmGOwxrVO9mp7B2QNfAyA==,type:str]
  VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:NHWWv88VJnz08/vnQtoeba1kB0FGHob4BDRH5iQk1aTRqYlvex0qljcnk1Y=,iv:hRR/eIb7wXZQlgj6w1cN3hNOy0MDidyoYBYSBX3ooZs=,tag:354PUmoT8874MMCKkda8bQ==,type:str]
  VOLSYNC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xG1Hw//CmgWYmkmHWjGBxYYm9Is=,iv:nIxewUWZaSV4adZhrlKu5p1aawXWtukCIjaehb58MLQ=,tag:ZxTuYarqwIm2FCBiVVi+GA==,type:str]
  VOLSYNC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:du/SU304g/tGguKZvJjazt3YehGrMo+Im8DFWBumWa+1HJGjuCdmGg==,iv:8frVXiIS1wz3HzgfTQP7tc19firs3DDYksn8F8D7NYM=,tag:uOeEyTz9KOX1vcUYE6Yu7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYld0TFZGZTNOK1IvWWd1
        YTluVkg0UHJXV2lZQ1FxZTBXZzN4STM3OW4wCnBYMytoa2NJZ1hDaGdRNGhiV3pS
        ZGdwL0JINVlJa1p4dTgxbXk4SHppb3MKLS0tIFcwM3hORkFWOENXditMM0F1VjJD
        c2pralNTQW9mL09hSzdPQzhrZWtjTjAKJW2WWWD0CGUot+j8JtFoc3nPeOcDD5ma
        1WR9/ZxPI9xet4eFBkRFFBAY+AD0aD/DXUFIVidyIyKkPECCX1b4gA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T19:31:51Z"
  mac: ENC[AES256_GCM,data:5Dr6xaxZCThUEX/vwoeDd0wPc1M02VMLmuKXLKDnNJZswjzmTFlq+hUZcMNUKUZJzS44VrJUNxsEio6SM6FOOsaeMYJTbOYSj9zDr3Tpf4XoPq/BVzOKybRyJBVRDf5U43VfZGB2vO3Gk8f1t9p7iDGXndwvnVxw78+9O+4fEJo=,iv:6OdXNG5g5Mx0rK8zhOqxYtM5axMzKAGJ1dfNH0zM3Jg=,tag:DCLw9qDJvEp3eJo8Sf8TnQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
