---
apiVersion: v1
kind: Secret
metadata:
  name: argus-secret
type: Opaque
stringData:
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:q1mWWyfo4rYryKJj3OknhHJHDHhwuM+oCvxp0+p3te1xom7Iac7GkB/HizU=,iv:nufv6dSC787RJq9g7tM1bfgfaVUcCSJ9UNK5sBa1FVA=,tag:xfBTGIgAoN+jDy0I85JapQ==,type:str]
  VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:QsDr2aIsIpEcUTc4Bi8gyv/LpqsrStbo/nT9zE8L6sbVN04mw7dot0ME2Vx/n6BKyuLuHax/mFpns+4TdIG9LYEhDPMlA98OQYvq/OCdSxU1u64lPRuY,iv:h2n6QWpMDBrn+jJ0fcqlNxGPaCsImc4/hwlFQwiIf58=,tag:msX3rmcCerFRlSDIdhvHeA==,type:str]
  VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:A0XXssC4nQgatOKB2njEyz/yFVyNAoYLe7ppwv7cCyRPIdyF/YTxHfj4jQ==,iv:ZB3T0lDXfhqW5TSQIxtxEiOb6xEGeDO6p8I6I4rQNVE=,tag:ZhM2m1HXv29rz/Ac7TiPhQ==,type:str]
  VAPID_SUBJECT: ENC[AES256_GCM,data:BI0PtvhkcEAzQTMDdTTPBGD0a7JkJjI=,iv:8ijrGx6udvSHJ6dVi+Rv4UUGCRknDIYUzDPzH1d3thg=,tag:ldDCVjcUEoKuOhkEzJFuhQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeHRBWDFsMHVaeTR5Zmd6
        MVdWMTNVWVJFdWZpbS9BOHczY0EzMTNERXg0CmpveTZzQkI4aWpMcXAwTGFsZFFT
        NU0xazFQbXlqMlpQYXNSUEN1SEdKTXMKLS0tIHlsMUIxempaWWxtOXJhNlhmSjBv
        SzlRQlpVMkJuRHRrWFpHRkdwVWVxbEUKGZwsmKL6F/UIilj1txh//Om/xGt9Ek4z
        sH/EDNf2xoX9nYFDt9kyTqcp1rwfwi32KwRu9Z5AF1xlq4KuWLUDUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T19:10:50Z"
  mac: ENC[AES256_GCM,data:4hkfPRDu4mmA7VFFXcwsno9iEFHrHUiY2mO8kTCXlWy4mv8fgqXzuG8WRbHUHrluo2qw/erT2gn7WZWx+5oIN163pRnDsfH/+xseSMyHPn0vy29WUBPF6P5BsBSAb2e+rKfKIHb1suMfxWiSUYBwN+9apHFkpR+467K5bPCGd6w=,iv:l/C45J0KB3kQqz2tSlLtzrLHUjRRPqmy00/OHzkLNVM=,tag:UYrA4M62WsT2jM+i5DYlLA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
