---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ghostfolio
spec:
  instances: 1
  storage:
    size: 2Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: ghostfolio
      owner: ghostfolio
