---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: ghostfolio-dragonfly
spec:
  replicas: 1
  args:
    - --proactor_threads=2
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 512Mi
