apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:m0lcBTni4wEOV89baZEcxtOkNhK8i2QoFTrRWJe8CI8=,iv:Nbrq+1HCiC7pf28to2EPB4xePbd7j9V1YESID/wDHmo=,tag:4RI3jFYgiVhb8VASFmyCug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYUZYK2ZxQlFnRUNZdzQv
        M0ZtTGZLMjJJNGFndEV1SzJheEtGUTdWMUFZCmVXZUdRQis5N3NjWHpMdmp5MXhZ
        YzdiNEV5QWFFUThtWHVDdkZPZ21GQzgKLS0tIHVRZ3IwRC8rT3NRd2NBZjVrNlpT
        djJ3dk1RNnNKTm5KTTRvNDYyT05EeUkKlycb4VGk0OUllKH+EfH8GHaI2jK5ZhTt
        7P6J7V1gnDuyH200Nbf/qzFc5T+iVnsMMvGFIwxNxHPNFu51gC1VoA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T09:39:52Z"
  mac: ENC[AES256_GCM,data:XBWXZnJPUIajad8mQoms7qbhcycuafvIm63eQyQo1GJ2cMWT2yUS4C8mJpI8W209ahO2UbIPbfiVFyxyBRG5P/T9Tlvv+LDnnwjAXn9wW7Iv9HHJ94zdDI7E1ZhyW3qSQCi1maSUe7KKJLC/KUCysRuHi9KzPlsvqUr0v1EOyBs=,iv:qHP6ioYdJSi/HaDh/DI337p2+l0BS1FNzE5Qf/lBLQI=,tag:wnJDdPyvywRT6zS1lIQlsg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
