---
apiVersion: v1
kind: Secret
metadata:
  name: ghostfolio-secret
stringData:
  ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:0dqNGBIyL9h2kePt2N5DTdLhPvU/,iv:ce2tu9O8P8U+8UNNMMqfTLw08WulibnAjeowmd9R1Oo=,tag:QcbajxptDRXa6SGmsyoY5A==,type:str]
  JWT_SECRET_KEY: ENC[AES256_GCM,data:Yl9GvNTKg2evNoeSg0WieWPa,iv:yVcDWFxCq654cXM8FoiiNm8BCwIQZMb4P6YI8vtw6oQ=,tag:YHMcXtGzodIGu/eLnNSojQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxa0E4aDNDWllEVnNqTWhN
        b1dCL20zSng1eGNqQ0lWU3V3UElEOFYvcVhnClk1b1FsS3RtODBFMVRQVU1LVHNQ
        Vk9GMDd5VzZWcG9LVWlmV29peDBwVk0KLS0tIEVwS1VTZzh5N0hURXh3MFE3a3Ev
        dmdjMUNsclhaUjZHdlpYZllMTlRiU3cKtFg2/9QR+Ccsz+Vm8NtA/RHuo8PuK0fj
        lR+nNKwc7ChHkJDejOxlr5NZsDdn5ZxTSYCqUiQLMKzU/j7dZJ3ixw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-24T18:57:09Z"
  mac: ENC[AES256_GCM,data:rP+YqzLBNM90fex5MPaz3PPk+QIh2PtWoVpLAccXBKNXpR0wLvP9Tvg9d8/AY1uyj0BT4uhBK7+asTNvFljfwd9rX68YFr5XliWAfNR0z8CcSkVSR7l+9nIfwnnlXUOoMUgfcm8hpmsTkYE4efMe0/lKRgclGQFo8qUVgKUAkMI=,iv:3TyE4NdmORdagMhf5/rW//66GYSmDwayefyefseuzbk=,tag:lt03YcMSFt0uonqKosBOnQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
