---
apiVersion: v1
kind: Secret
metadata:
  name: ghostfolio-secret
stringData:
  ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:hOLX/E+Lu3GM0CCxuCfCNBPMFQmCfCsynXRyfqy8uRWN4AdMp5gkSrYUiEA=,iv:44UlYFguG+sDVYTgrBPSBJ19XmiPGEeBzb9RfZJ9VlY=,tag:WSJuVA0+hS0I25wIKfJpvA==,type:str]
  JWT_SECRET_KEY: ENC[AES256_GCM,data:s9xgRK88IAE+xx4XdDJam+7dtz3bE2j0QUopKm6lGOMBD+/DVCTShC27KEg=,iv:43j+i6Ze1vGM+xaJA+KNZHQkfZnGnUA2e0UIb9B3Ndk=,tag:TG/PpEWrCxyzYGbBZVElBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxa0E4aDNDWllEVnNqTWhN
        b1dCL20zSng1eGNqQ0lWU3V3UElEOFYvcVhnClk1b1FsS3RtODBFMVRQVU1LVHNQ
        Vk9GMDd5VzZWcG9LVWlmV29peDBwVk0KLS0tIEVwS1VTZzh5N0hURXh3MFE3a3Ev
        dmdjMUNsclhaUjZHdlpYZllMTlRiU3cKtFg2/9QR+Ccsz+Vm8NtA/RHuo8PuK0fj
        lR+nNKwc7ChHkJDejOxlr5NZsDdn5ZxTSYCqUiQLMKzU/j7dZJ3ixw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-23T20:23:03Z"
  mac: ENC[AES256_GCM,data:X9vfJpy+kxplWR9WBoKAybRYO/IOCkbFrAYu2sumjLFgi6QkzyPqKJrSOD2Fzsja3YGw8qZoy+wO89W7grDErCKHwkstLOEH+b6JQ0U8Y319Ezn2OK9eS6TCUTMfCk06MgMS2UxEFK+CD+ASSQ5oGR11xs7tlL/Alc1dxc88sQ4=,iv:A0SDUyFdV/Uhd1hkWvA7+5UvYlq6J1vQgVBUdMRSS7I=,tag:cApg2eaFxwYOOaBxrxlOYg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
