---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: your-spotify-mongodb
  annotations:
    resize.topolvm.io/storage_limit: 15Gi
    resize.topolvm.io/threshold: 20%
    resize.topolvm.io/increase: 20%
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
