---
apiVersion: v1
kind: Secret
metadata:
  name: your-spotify-secret
stringData:
  SPOTIFY_PUBLIC: ENC[AES256_GCM,data:vI+L2N+3TVD0C3SY8cYu9HExBvZZoRbUQSHG6A==,iv:zJAxmqP09kWBmic8w9IyJC3ybeaoz9+6FLGt3qecJds=,tag:q3dh5eagW/ErebRkBj0XCA==,type:str]
  SPOTIFY_SECRET: ENC[AES256_GCM,data:vdevqBwlKjaDcTNHC38HuArzvn2waebjc5vocAMf4DQ=,iv:kN5vS14sLnKcaXAYXaS/oHmJ38BWJGMMj1u6s5iA7jo=,tag:OFtxHrg4z3JlqND6K5LeZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROVVNckZ3ekI0bkVpeGZT
        cGZSa2RZR0hyZGVaWGVvWjVKUWpyRFpEQkdnCkZuY0pYUlJpZCsvUENzaVk0OHRu
        V1BnZGY5S2FFSDFVOWgwN1AwclVhZlEKLS0tIEQ2K0pYZnUwV3ZGRS90TDVOb1Z3
        MTI5cm5aRmZaWmV6Z3c5L3M5ODhSdzgKfrYVmQA7FSwwF9T9DAiczBoZ6GQNTUrH
        Vr8y+TqeCcVxovpEj5DrOZD8tboUoG0clnMa2IcyVCkrAjTc4rOung==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T18:01:30Z"
  mac: ENC[AES256_GCM,data:FBVc0TcXzD8hRd/Ib8lYLBLQFQTv2TcV0f26pmUwqoVcHykqzqQ9E+JVuEmBjLpbzelIPtduwNN6xdoRxEpVEsgaNf4S+KG+GoZe6Ct3l1L1RXo4ETZD6b62z615MT6mW/fP6v1nabgyiO1o7VpoxYV0vd5h3/X2YoPjPA6X7Y8=,iv:nvFAjDaytld9HFW5tE8NHHeRURfeS+lvti8HNnMY/FY=,tag:oESaCXxvIGjZ270fy6+gaQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
