---
apiVersion: v1
kind: Secret
metadata:
  name: your-spotify-secret
stringData:
  SPOTIFY_PUBLIC: ENC[AES256_GCM,data:3UdS4QBfQBvzYxm/6dhKxRQqtYH0TvIU6IadRuTx/zk=,iv:Z1JAKpS0+rYPJe/seVdntgV1h3Qj6TLVdgaxBchFPyQ=,tag:kQTTwBDXo0Zxf1kGk4jAcQ==,type:str]
  SPOTIFY_SECRET: ENC[AES256_GCM,data:244kcs7qnrnaVpVqVRnnHiAbKWWCsbjAvuqdF2l/qEQ=,iv:9MpkVjcQhNB681adNCZNKFqNMnby6jgnbm6/j9yA/sU=,tag:Kt3igAifq5jqhoTsg6YyFQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROVVNckZ3ekI0bkVpeGZT
        cGZSa2RZR0hyZGVaWGVvWjVKUWpyRFpEQkdnCkZuY0pYUlJpZCsvUENzaVk0OHRu
        V1BnZGY5S2FFSDFVOWgwN1AwclVhZlEKLS0tIEQ2K0pYZnUwV3ZGRS90TDVOb1Z3
        MTI5cm5aRmZaWmV6Z3c5L3M5ODhSdzgKfrYVmQA7FSwwF9T9DAiczBoZ6GQNTUrH
        Vr8y+TqeCcVxovpEj5DrOZD8tboUoG0clnMa2IcyVCkrAjTc4rOung==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T18:16:52Z"
  mac: ENC[AES256_GCM,data:lRx29dLwlGwCQ3/9n1SU1jilqH42C/aQLg/4u1d00jW2iOWjMdC5JibPdkYEUPNPK8CwBuWENw3QWnCU8xG32e/BaMKs9Xl6ehP0MEtU2VyGOjRDSngePAWVw8wO7a/EV1Hbl8HfgjaLnM07UwnTl0AQPlTj3SOdheqN/OFeUpQ=,iv:jwyO9k0eBUCRzT4BfHUHHazCO/OSAu7itcKr3k0mW2U=,tag:GjhDxhP/fRshzf1ANcyFug==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
