---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  instances: 1
  storage:
    size: 10Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-secret
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord
  postgresql:
    shared_preload_libraries:
      - vchord.so
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
  enableSuperuserAccess: true
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi
