apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
stringData:
  username: ENC[AES256_GCM,data:1COT7m1/,iv:KuuBTCkORHqWFAjUHMj2KXZQzG7MFbDoHbpqs/qbj18=,tag:KC4Ox3PZ5ZnZfcIYmMv48Q==,type:str]
  password: ENC[AES256_GCM,data:zXlmcVnHwubxpqI/Ru7tkhmWB+Ns6Dhr3ygJeBzdvN8=,iv:gKJTXYGrtPYW0yyQHf86RvGIQUmACAdshCe+Nsa+1hk=,tag:s42Vpl/JFdxHRnjs6wUEug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRk9lZmU0VXFhYUtXYXlP
        RHJOMDdFVkUvS3M1ZE5HbmluSXYxUHNsTndzCjhzdzFSRzdvRDBxVVJHNzNQTnFl
        dXhVQnF2Q3NzWmVmQ2k4UHRlMEwvcUkKLS0tIFJFMmZzTjNpcXRjemxpRDR4ZUt2
        ZEloMXBBbDBTNmRMTWlkaFJxSXVRa1UKjhak5/CbMzthPg6NrtnkiTcKFppZTdQj
        E3dRJU1NRGL4Ge5cixyMWUNoQZyxHdl/XV1n618pLq220v/LnwPe3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T18:59:33Z"
  mac: ENC[AES256_GCM,data:neoW8toJuFqHPdv3KK8rSy8xS0BkqNHfzbxIubkDz/e3FJbvEfJoNnUe4WmN3BuMYwtGj57zUsvx2wMmJJoi2IY9bo5aedZoAcq92E7xrOm5hIS8n1Nii8iZEpQcVTTNDO2NDmWASX4hTSWZpt/XxQAHPgTJbqGa27mjtw+bH9w=,iv:PEMl+43w7l9QSbuEtOlia5X2XAOQdIkiPqUiLvu+SRo=,tag:3CG6euIv9X5y9mLKSJC1NQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
