apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
stringData:
  password: ENC[AES256_GCM,data:yiZha9Jgd1ulF9dFk/H5ihm0titXCupTQo6IrJpTUAk=,iv:3XxR5c+/bJLhZCsfMqyEPC1zJsD/N5ec2mul+XoZuIQ=,tag:94b1aE2lFDPfKBKfwkYjww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cXhRc1VmK1drU0M3YWtM
        M25xRjdTSWtYclp6OGpPZ3dKQ2hZQXMyN25jCjVkaWdRWVBlcUxHK291cmhFcHgy
        NTNDdEs2WDZEMVg5M0M2UU5GK3dqYlkKLS0tIHZscnY1RE9oWE1TZVRuY0k4bmRu
        L00vNWVnZUVuRldCVDdwcml1UnNjNkkKkgGKTona5jRutOoPNW0hARdl7Jp4DcJx
        HEMTrCUh01R8eCs3YkuCpMyx/DwOcTWMm8zqjHYFrVS0fWMuhzd8mw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T18:42:34Z"
  mac: ENC[AES256_GCM,data:2nMTVcV3MdLRFkx/QWCsVYlgeqwyI20ZWJSiAnY4ASihvEzWql19HQVLhNANZOBCpY+LHTOoDx2mCcOnLcPaDsJb1YG2NompofizV4cX4yXHGj+2N+3u9frsms0ycG8svHCWwfkRBzhLG9RzYpEJJuzkLIx7zfaP/7HpTp6QMWM=,iv:1fjl3nqQpl/1PZct9B5PHSAKRd9WHLcGKKd3vM0CotM=,tag:C01NK6Y7so02dZV1akv5IQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
