---
apiVersion: v1
kind: Secret
metadata:
  name: stirling-pdf-secret
type: Opaque
stringData:
  SECURITY_INITIALLOGIN_USERNAME: ENC[AES256_GCM,data:hhlM46o=,iv:TaUKxM5OuyeeLskMgXYwJqhQgn9jS22VfHJuENluvb8=,tag:nnjSiFqHecbnwMeTZGLiXQ==,type:str]
  SECURITY_INITIALLOGIN_PASSWORD: ENC[AES256_GCM,data:s6GsTbQe4L4iJjQKHakXaChqsnxCdvpXUvbUza9gaTeWcsyQIQvKBQ==,iv:z1TvJBzDjwSeB24k7s+mkR1RebvSTYs/CT/wkpuj9A0=,tag:YIa/GANxhCPF84l6ZnL7PQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBralVpdEhnVC9EdVRseTgr
        NUlUZW1BQzBzMHdWRUtoL0szNnVjeTVUWjNVCkpSeTQ5RkN2bzdXdnhBU3FSeEhJ
        dEpqdzVtQytBekhsRVBXZ1lUNWlQZGMKLS0tIHJFU3Z6Ulk5eENkSHhtTVozQ2pT
        M0o2bkhVem1yRVNYTWJOSHRNbEt4QW8Kcqwwje4w2PMs0Gj8up+GWG5axlxPeUJM
        8oZJXKukJTdLeKRFC8NqpLjMEvJp8oOSW5nNepfZ91eJTv9pypvKJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T18:08:59Z"
  mac: ENC[AES256_GCM,data:qolPH4UZyeWG9NhTeimiNbLqNUFmaFHUplMhdgVS/8DuYN/MFkNnPutQYjHbW27qQkZUo7HgGivvjp8hGqY0cIVJC1ydU4/IM9CK4CaKrMigDNIStUhwG8Xl5ULYgMTlDodpSvS67rlpwCWrakNllGEOB1N9AC+UZA7lDnHCgTA=,iv:v032v1NUmnVurLxqv0pTOfC5MpSQmMkHVMiiqTJVO00=,tag:a4ogd8+Y7cPheQWN+fFHaA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
