apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:MWgnWA53ZVz+8AOZRauD7nJ41zz2FjHc9ci2fhGUZ1eZDJ6MtoGgZQUV6bSnUlsrAwpezQVEzBCB+ZzGp2Z77DXqYg0VjJDmC2KQCQTcg9xSrsc3l/JhO0xSPcANeSnnzOAIW3KhUL2ExbH37MqSuzdcOMhB0N9Avf8tjc5JFvlibouLRM1H/jwgphMCrSwwumLHhADZUXtnMLXuU1/UdJd61/pkjyC7WqzoTo4zrnA2hsHA,iv:RF0XyHTDjXvBaR6TPu5RFkiGLD3s/ODOmVz8L3+aCqQ=,tag:4anIkBr/yHBzTgAHsQAn6Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmJ6NmUwYndTWUo3SC8x
        cnpGVHJFTHlwaGgwOXRWUHptWlByQnYvR0NJCmpTV3Jxb2c0b2FhYnFPUHdybEZX
        MzBNV2cxTStjNzBkU29iNGFhM0RTbVEKLS0tIDRsY3VWUUpYS0RaVG5SdkhWWHBz
        MVhzemdIQldRa2U0dWR1MHNlYjdxK0kKf1l8NywajAv5txnulPuDdaTseH+uLSkJ
        4wJlSYgn6zBvYrG6xXuVEENtE9R3v2dAou8+6P3hwdMRIQjNHsWUzg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T09:39:52Z"
  mac: ENC[AES256_GCM,data:gu2lATXK80tFCdRdorEiMCpGKQ50kt32zAvkkt9JuaN9kIMk1yaBTPP8y6MGN0o1keYDHeqSAY0BM4+zwAfUu8cmEMFfE3SUWculhff0XOtYTkkcUx7sdppxNcUQzTaadNyliJyNY39nQj/kFpRCzVGvuHiABz4+AfeN3mVJfmw=,iv:Qv3Vh69vT4OIhho8ckobFZMPnyvK8L21luvOZ6jnlyg=,tag:qaXiH78UMYlO3Bfcut4/Hw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
