apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:s7lxtdSaB2MYKYOnCcPcWuEIURSy7Fui0ZxPALf2Q/55tfOUuFwBStyxR53OUy7G/OdwjIw=,iv:eI43u6Gl/cCLtS7XeZ6NbiIu25c6Qyow/GrCU05tqas=,tag:VmtSF+rzTis8zc7Comzriw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Uitnc3VVYUdRSGZvTFl4
        S2p0RjhwYXFjd1ZUU0s3WE5XQTl1VDhDQ0NJCnpsaHRuRWFEMFFQYXByNGM5dUlo
        UXEvSXByS0NjLzlkZG9rTjQ4bGdLU2sKLS0tIE5tQ1hESXNlTW02THdIbjhkbmxp
        eDJxK3A3blNhMHlYa3RYVlltVGwxcGMKqg9OM9lZ5pwTk4E5f2Vm3C47fHo/Wqtx
        gcqHgmK2JE2d2kvPtOi7VDSutr0QNuoFxA0c3A2P5wbEpiC8yhCCcw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T09:39:52Z"
  mac: ENC[AES256_GCM,data:bafXKHyXkS0U9VCGmuBJMBkhV+nI0lw4MBaYB61k7Fl3navbgni9s7Qsmf49pr84iAPOk/FEO7vPPILg6q3TG62Tl0jF67OMxVXeDwAL7JBYOZ785J9v7gt6fF5dF3UVZiXt2laTuANJqwaA13VLiJ5MOIqhQjngyk4KupfZ6hs=,iv:lLJkIrFVmL09VaIlAYLzz6mCCyEe8ko0RxSAYHn6/0U=,tag:HceoiD9KSC6akJZ71DjGrg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
