---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argus

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./argus-db/ks.yaml
  - ./argus/ks.yaml
