---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.100.100:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.100.100"
  - "twenty.marco.wf"
additionalMachineCertSans: *sans

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "twenty-01"
    ipAddress: "192.168.100.200"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/bb0ba48a52352c699781aeeb4aa1983b80ccc778c2eac94590fe6b4ab3c0fd00
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:a5:f0:f7"
        dhcp: false
        addresses:
          - "192.168.100.200/24"
        routes:
          - gateway: "192.168.100.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.100.100"
    patches:
      - |
        machine:
          disks:
            - device: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
              partitions:
                - mountpoint: /var/mnt/lh-storage
                  filesystem: ext4
          kubelet:
            extraMounts:
              - destination: /var/mnt/lh-storage
                type: bind
                source: /var/mnt/lh-storage
                options:
                  - bind
                  - rshared
                  - rw

  - hostname: "twenty-virt01"
    ipAddress: "192.168.100.201"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/bb0ba48a52352c699781aeeb4aa1983b80ccc778c2eac94590fe6b4ab3c0fd00
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:46:09:5b"
        dhcp: false
        addresses:
          - "192.168.100.201/24"
        routes:
          - gateway: "192.168.100.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.100.100"
    patches:
      - |
        machine:
          disks:
            - device: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
              partitions:
                - mountpoint: /var/mnt/lh-storage
                  filesystem: ext4
          kubelet:
            extraMounts:
              - destination: /var/mnt/lh-storage
                type: bind
                source: /var/mnt/lh-storage
                options:
                  - bind
                  - rshared
                  - rw

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-extensions.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
