---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
spec:
  dependsOn:
    - name: immich-db
      namespace: immich
    - name: immich-cache
      namespace: immich
    - name: immich-library
      namespace: immich
  interval: 1h
  path: ./kubernetes/apps/immich/immich/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: immich
  wait: false
