---
apiVersion: v1
kind: Secret
metadata:
  name: ntfy-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:nQPTNgRsbYBohTmzv3f4sXqaKup2zO0V1M/Wcd6FlkwnieHiyn36UwBfCZ5onBDT0ceAGhb8zINCcWC7ZEhD33C8C7US8Rm3b+pcWA==,iv:1q+Y7+Mw9BYIqXTdqvsOIRy4NVgbTc2FmNpkZpEp+JQ=,tag:ui4mZbBdyxLK+vHKtauRPg==,type:comment]
  #ENC[AES256_GCM,data:giP3uf7/qrNzZir5jNHp1A+M8h0jJllgOdD9Q3hMtoN4XzdGtyud80gTvSo4oUr23uW0Eq+H7PRGXIV1lzpSAmdx+lSbTg==,iv:aXrqZZYRG7Ewkr2Du1QmIx8ZkAIuLEu7BNy7P3YNfnQ=,tag:aQqwzxQQhd93ut9L5qHPQQ==,type:comment]
  #ENC[AES256_GCM,data:KNwl6g+p/x20pJyidIk/9k08fzEbbPU+xBdc9lhgtSo95mIWk5nbErQRK3rPv9bqrPcK9uz6uN7LInGpMisJRKA=,iv:4kRSgjP4jSJ9HUnjPHTqADmkrUe9TEGs3v79ltRy24Y=,tag:rXI7ta57j58VAUmf1va74g==,type:comment]
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:ZSdZC9W5rLwFMdtRiQp78mt2fhNfbXZfhZKkhDLk1hV/sR90iSPLW3HigXH3QochFq2gIeUvoHzX8FyZB7GBSK/S/uH4Otc=,iv:FCyeE7b3xWWWgRZ5gzbdf8t4op9n7bC+GnCiyHBoFVg=,tag:2POtSIk0jGKsrpQU7FCbdg==,type:str]
  NTFY_AUTH_ACCESS: ENC[AES256_GCM,data:3AMTO1ygogE4tg==,iv:iXQmejQc4ZpWcNqPt6hyzxkLwVQjvw+AHZsHf+8n3FM=,tag:/OGh0TNHBVHKN+SWSNrsMw==,type:str]
  #ENC[AES256_GCM,data:BX73ME64szMGkLhsTieb/k43Zgoy8xCl5fA6HzO/DggSUSetZt6omqzrPaFBF15QTROqCr7hyDsQ2q4vduVRcqtgwcXIK/DCO6o=,iv:84k0Zz+l6qz+K7lu8X4qGS5sLMJzeIW+TzLSlxfydv4=,tag:1pmx1fzW31LthDm3K1azGw==,type:comment]
  #ENC[AES256_GCM,data:WNQaNzZZno5L8R+ZyWqDaQa4BfA+qQeNNdpFAqqcVvBqv55InU1GK43Upyt/W13abgwKkyenLuveHr0NrStf4ZzT47DQH7nLZg==,iv:wOkgPg83SWGDukmgXbUsz0RpreRY8VUolp9E1E5Sh0k=,tag:8m0nvJk8gF5fzoxXaXjO3A==,type:comment]
  #ENC[AES256_GCM,data:wwiBRhcJH7rVQr4u5+pDpmYmASGlo0bBoIz8cSETnEhG2JZBj2u129iVlcVh5hh1cmxCNHd58xIgoJw=,iv:gEjAjdWS8PCfVx+oiBDak8EGLKB2+VR3d9uxmbt7kFo=,tag:IoXIO8h/TJACRYhxkO8kxg==,type:comment]
  NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:2l6Zr3gricBpYWedzZgAoRieZHR3wwMPqi4vVaUGtZthFuzjKebJhGg6i7wqVmBF6VjG,iv:MAZ91UmIDS7uqLMzx4Gwq2fGbRcXkilzORcciRf9kis=,tag:FErbMEMFDsBYuXExyIffSg==,type:str]
  NTFY_LOGIN_PASSWORD: ENC[AES256_GCM,data:3mbBEkS/EsKms9/l5Xgiqr/wlVtI1RrsytvV4PqwgiE=,iv:rlb/NfPDs/qebQBiLRZNdXD90xteDjVzrakwciBX69A=,tag:KqlficGdo/JnooW40fy4Sw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWEZCNDNCclZEeDdQRlJt
        bHgvS1B6MFhzcEV3RFRyM25RNlFiblBaSno4Ck4yMmljL2hKdlNhWjhScTNSTkpC
        WnpLekdGUjZuMGp6RUhDZFBQT0tpbUEKLS0tIDBEN0N2WlRyZmNuTXJwZ2RFK001
        MWRGWEdJaDdhQ1dROTkwdEZ5ZXR4N2cK8o0zLw939BMnm7tj375jS9Z3rd7k9pMJ
        SrZ7TlaHsrDmSzsyB9MmZM2pa5i/hR9aHilN1uGQe1UuoRcpd+ANkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T18:59:51Z"
  mac: ENC[AES256_GCM,data:WlzbTRTbhUT/vwR9o4vUzOkJiFZ5/ZlNAFfMAB/skexNGx+EHLHtrSbQhYePLG/enQuGYBoVTQiPIKLYHPzxsLNqOnaP5uJlTLXn+i65x3YnmkTsJA69JuYlb550T0rXuzu2RbufEWvz8lccGlH3P7KXCIOGT8RWB91Ek7UMCsQ=,iv:4jq7Q+tM3o6yDqgOhPDoStOrRNVwTVNiK3HaDGQM5mU=,tag:ISmgkKBgZnni3ce2Z1mIbg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
