---
apiVersion: v1
kind: Secret
metadata:
  name: ntfy-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:6eqNH+Re64c+jyvlwao1JrusCII3OmujIzJU73boE9I1r4vjokeC8A1Fq5VOnhQOCCdfmtxAUCYaePIVY5uciLiZNt4ITduWlAlt,iv:9t7eh1zidHg1CcMYgLMm+tTo4kgXhPVZKRcm2XgL2CI=,tag:xPr+vfdpyhp8AsNP4NSBGA==,type:comment]
  #ENC[AES256_GCM,data:9p5PWZ26fRsyCMfOq6vHxhJjc8uPW6iVJIJyjfAEuWigNZ9yP3ljKiXGhnUaay23,iv:smjXU77ZDzxohj2Z5GZBdIMbxyXMYNu1C93K7GRQDEY=,tag:oTmSEo7FV/423BCYmFSpfw==,type:comment]
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:pZfxhnTtFv59ZtrMaiRoZmlC4DaACtcMPwQ3IoH09tWxWf8hTlOf4JuSr6c7sL8/ojRS/4RUIsiXt5oSOx7NbpFbVPXrLL5O,iv:92Z6BpL4Otc6BZxe0HWiNB8J/XzJ6Lt8jTIffXuHMSM=,tag:dbCONk2Ysp8iY2BZxna+jg==,type:str]
  NTFY_AUTH_ACCESS: ENC[AES256_GCM,data:MPr/TfxCcTSuoA==,iv:pT6ARbiwWR6fUkCguNFWsP+ERMkK23ZTKa2k3hyDaq4=,tag:RRQrlfDyzktOU76E6Tt2Ww==,type:str]
  #ENC[AES256_GCM,data:Pe9a5F+W5W3p8KO3IpovdP07MFyx6WFH0JAeF7igayvOrxpyEK0=,iv:C7zjIJm7bChHs6tWMRw5zkVy0NKeU2HX+kKZiCwwtho=,tag:fhUBjLbF99hqkRT83Nc54g==,type:comment]
  NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:C6y3yshHuNESKStp67OItWHKmkLjxbp5iRA2VkZ991cnceVK3uTHARNXmVo80U/u9WZ3VA==,iv:Ssf5XWlhK6bAwD3AOACMEqebYqsGSQzTKNXz4z/OOwk=,tag:mQlpEs24U/e0vdOeplXszQ==,type:str]
  NTFY_LOGIN_PASSWORD: ENC[AES256_GCM,data:xxUnwNDWdP1APMcuvcc/4yhi6QVbgnQE5Xdi/kye5ig=,iv:et76W8GjqH1LGeU+UiCCuKDxl27WSSVh7+VLSOc+GZQ=,tag:9Hdx5yVLzNdmlrOUzYP3Zw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGN25Wc3dENEljUG40VmFO
        Wll5ejM4aWdLSnZ0cmVWcjQ3elJ3Tzlod0RrCnFxN1pReVNEL0FRM1lqZU1DWFpL
        VXgxWlVFN2dodmEzZFZzbWpZQlBKU0UKLS0tIHMydVlLNmhhL3NGdWtqZG5sNy83
        b1RRQ2dCaUZXTXdWUG0rOXR0ZTM4MHcKqSn5QCV9FYm9S8dILM45RyE345jPbq/f
        UAtNOtmA9P7aiKNi5BNtd27nHzjN86034QPPQkGgbo3cK66ZJri4Nw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T18:47:34Z"
  mac: ENC[AES256_GCM,data:LaEcqWixD4AH8w0AKPC1SB+emPjoCctmvqQdSnipjoL65+zT0j4mojnbZQUI2Yvf6TQNJyIHmmkdnPICbUtzrD+DPdpdQ+OO3qf0gTbPODDcaaH5aQ4PId+1wyxkqtqX8wq0WRaIbEt+o7XT7TUwI46n4jKhutrrFVlX3qgGXQo=,iv:woogz4y+hI9sSLZbOGlpuRIgA81EEleznIlsfq5GgYM=,tag:c/uSolNxetITt2tliT+ADQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
