---
apiVersion: v1
kind: Secret
metadata:
  name: ntfy-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:INLn4/4c8Yp0FGNkVyZeZD9akgYsbHHi6uSzeRXBYUsrmLSvUVTmukyPdx1TYyHeECkocBKE7G0jf+82XQy5v5vKLOnQsgtqrfW4Ow==,iv:eTvMq87OhpJNQM9OaZbJX8TrmLOY91cXGQJ9Z6tRLE0=,tag:BACcRHUugDnLCuf21NA17w==,type:comment]
  #ENC[AES256_GCM,data:HAEg8+xJCFv/4NGJvYHDtIVUBWZBn+rg1qaf0EOMThA/zIYkSSR97B+IG2PUit1o9RR2cGGABnt6/AM+sOy3iyTy2kDbeB5J13M=,iv:O22CBfuGoLuVn4I2quHUmF8nvrF8S7tq/pcgb3pMRoY=,tag:DnIz0u/YmcxYl2rgmKDgmw==,type:comment]
  #ENC[AES256_GCM,data:+CCSl4nRuZAPppynLgn2WlIu5PJUQRf3+zqm3m20HrXiJERH4EPv3/2UoSzI3FPwMRlLkcyFydTAo3C0y99eRdZMnQ7IFWccTEzb,iv:RWP9wnKNIylnCWPh67IRQsy8OQF9Zh8FO8akSynWLaQ=,tag:do3zYQOtwWMfokLB871Rgw==,type:comment]
  #ENC[AES256_GCM,data:Iv+7zc4wsrcv/b1soh10eegcS51E8xMg0cCe0E4faqISSTxDppOfELwWiH5ab1rfmJgXFxq6j52GN72jdrsyVYo=,iv:Hin/Sas9Gi7Y+PU9B6W1XHaF7cSDnzMTynyZJW7idNk=,tag:gn9ke2VgTcWe1zAMKse4ow==,type:comment]
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:YP/9BAaEyf3/4/08ue6OeoRCrNYOci/xmK9kF1AZ5pKNxX+BWHIoAF4XSc5tVhWYlPSzvR7H5CtdLNepuB+558c9llKUR3E=,iv:ISAvC9Ousuxa6w/MGWwXR3QbcyPxUol4fAWZPro+MeE=,tag:ZdqyqVyxK6UxtxxGY90HuQ==,type:str]
  NTFY_AUTH_ACCESS: ENC[AES256_GCM,data:Z/01zB41WsepOQ==,iv:GCYGlVchu8EUXOF0T0ERGAXBK2W5YUydJ0mUInZiF/c=,tag:zsvLRHh9OqpFtq5rVK7HUg==,type:str]
  #ENC[AES256_GCM,data:916ibokCt9LV7/MDdsKUqQIVayVU3oVorR1ZU/ifGvrZ9Pc/bzRk7R3HZ3iqN9dsMepvjLys2OdlkzKctDwb+Nv4IbbjWbUz7E8=,iv:WRUTpzBFj/kGlReWfDrkT2CpAJZQmHE521Me8zXEY3M=,tag:326c1T7yRFiNGm/3lID5/A==,type:comment]
  NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:lNWWw0Wm++TMPbxDxLwFi8uM13M2EVxFnqciZ4yfVeFIsF20CZpT7IbW/Q2xqxf4P1MCMg==,iv:4PjPEP/RSJ12wRzbmz0sThCOoduw/SrFUlzf7Qk3RnI=,tag:Jxn8uSLRNBG3C97xpRWmAw==,type:str]
  NTFY_LOGIN_PASSWORD: ENC[AES256_GCM,data:IE90gJpHzrxDIT0PV9w82B/0x/9sjIgoxjExvykhR9c=,iv:XSB/AcGnX0l9G5WDvn24zE6X4Wb1ILECvVZRxvKO7X8=,tag:fnqk0Pi+uubCRI1C9zczFw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2V2NweWhaQkVmTDh3aThH
        aEh6cisyTS9lZG5NWVFqMDBTczJJL01TdWxFClNWWElQaTNoSnJDN0lGYzA4dm1l
        Ym4rbjJjUzY1Rzh3RW1IanpXK2NMczQKLS0tIEpzUThNaGx3dE1VQTVEYmFWK001
        UlZYQzA3Tllvc01Rd3ZaN1BlYzVneVUKQwHnaABy6Z+132clqH/beTLrRrLe3ynm
        9FJ0MGB8GMkjY1gqbHMVWzSBgCdIIxGU9sfxRH0Dv8B+ck20H0xGyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T18:54:31Z"
  mac: ENC[AES256_GCM,data:zZ2cLnNoKoOz3GhtnquboZagImDntpHUtkHHRe/STM4OytJslJvrsZbggI4IG5HXmyynJBE0KGZ5B4fRBkd9fdlL6hGz4vzenDvTjuk1yaXeeLK4I7Q1hGYk3er/KAVpzSakFYIko6VNLCwC3ZwCYghuyJpriXxKvW8mSShjw8A=,iv:o3vDkzu5mA+6+IvhScJHTJfCF+zgZ+Rr4yo1Crw3xkA=,tag:CHk25DgN2ThbkUpgoVe4Gw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
