---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-ntfy-token
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:NQT0ze1q3zP9OA4zORgTnK/r0nxVO2FgtoqIqCvcIIs=,iv:DkoOstvIrZMcHe0/pALBosI5tWz9uSaFBUo37BdL7Mk=,tag:67Nb9xT2Jr6UoxDBccg9cA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK2ZRUjk4MDFwNHZvWTBp
        ZlFvbVVld05ENm5YVUJRZzBTamhBRHNaNEFvClVidXFwQytSNjQydVU4aUk0UEdY
        QkRrdnJvSjA4Q3NiYXRwVUhzdzB2QzQKLS0tIDJPYzN0ait0Q3lXcGxTSHJuVHdz
        WXFoQ3hORmlEMUErN2hqeGN5ek55MXMKN0DFPqgHkGxvaAZRBWTM++/t5oSvUKPV
        0NhFNhdAZ3zZ+DJXZzJB0VMvDJFmpyn5jAZDvfUjORX24ia20eWnMg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T18:59:51Z"
  mac: ENC[AES256_GCM,data:rZ1YoHgQVf9GVDDCdjKB6BbdOno/HdXU8KMUxCO7Y+gnaS9yAlIxzkL5/gVHLCs0vDc/rdLNLhDx5Rd8C/9h+bSz60vaEFCaitKYQIRtdgCUGMGSC9m0YDa4k/8McSRbsiOHYFMPnmsw27xblXi3CTGfvRiYyk9umIZKDiVNpP4=,iv:wxeSkh23v8/ox6Eqmp95DUh4DHioMucSc+3/Uj0plaU=,tag:/xlbB3NrKwmBO9/+gAIavg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
