---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: longhorn
spec:
  endpoints:
    - dnsName: "longhorn.${SECRET_DOMAIN}"
      recordType: A
      targets:
        - "192.168.100.101"
