---
apiVersion: v1
kind: Secret
metadata:
  name: pz8-vars
stringData:
  PZ8_IMAGE: ENC[AES256_GCM,data:mz+OyTfBEC582dyvG9lM2s+rZyKmO8eXEtJFo4match8VQ==,iv:vUYyplRESUoEhY7PEj7O04rFIPY+zRhz3LNHqim3Tnw=,tag:VQ2d0nFmoYc2q+cFaLYhZg==,type:str]
  PZ8_TAG: ENC[AES256_GCM,data:Ve36TshqmGHTXhJy8i093la+n0cpMUFHLYFt3HNIXPKO4skhFbMEf0mpV+Sxz8sIyKyA43p1dgXGNHcy+W1Q7FqZcRRztak5cSWz8sxcJEWxDOA=,iv:xTmLI4lbCnTeSma2Ry1LNLYfo57prfXGXufCxq6pS88=,tag:mgSCiFQ48WIyzWOOCQZNMw==,type:str]
  PZ8PRX_IMAGE: ENC[AES256_GCM,data:dDUcvN7SfLAFcVKWhPy6qOn7DZbAIwDoube3E0k=,iv:Ln9MiVBf9g8RKMhz3oUOr14/0r14O1djIZ2IO5/b1OY=,tag:n+DmU1oIObs4wzQbQAKWbg==,type:str]
  PZ8PRX_TAG: ENC[AES256_GCM,data:N296wmIBuspKRhCwPl7H5lnUBicvkNlpf6kP2oDfeIFKFtbbHOslfKcwkZPYoz4ACGbgnPVpH8PirnPyamTpMyvmY1+tHbNTKKqkytye,iv:TgL0Z3cMZfsGUDPS8950It0vQVCF3Kc30cDAFBzqWY0=,tag:OcNFY73rsjKG+PCndIMeXQ==,type:str]
  PZ8NET_IMAGE: ENC[AES256_GCM,data:4eKo2Q5V6lgeQbJ+aFQ1XFN4fQSU,iv:HOB/oTA4T/NISPcY+FtdOl6gA9BbY6AfEnrqc/xJnKg=,tag:/R2y1n7YhFBL+sxfXsaVCw==,type:str]
  PZ8NET_TAG: ENC[AES256_GCM,data:urrfy9d9P5cIrB0tWy7sYH80aV16naxw/b9yZ2Un2X95ftuLkzec10prsiLVx/laa16rma7wkU57UNIcLaJyunz0VRRqbyhwuve8/BujaA==,iv:oJuYQAvBQ4e8w+95MRA8ngOetWqC41V0JdspCfitWa8=,tag:ahMrmsthWA3IAS4KKP24Og==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WnQ5WFJkMnhzMUlRcDAx
        QmN0MWFmUFBCc0tzSnBOSS9pQUh0Y3BtK25FCk5rN04rR1FVV3duRjBMWEFycVFC
        QWd0OEF0cHNiZmdBQWpYR0NPeGR0amMKLS0tIGkxaTdyRVdTaS9NZnNDWHR1R1Ax
        L0ZqdjNoVThoU2U2QXpzUHJENmNrRG8KA/Jh/n+lVgWYg7SuAxJFJmWLTmbWoKJK
        LCnj705nTKS0UX9RWO8+aV4a5NKiamHqJ48HlUm6Y5DhGlbYJxDm0A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T14:52:58Z"
  mac: ENC[AES256_GCM,data:MkgSXVqcuD98rTBLxKHZe/iG0X5jm2VuXWJyowVn5AJ3ix7h+jAdHDZBRqX41QxyNBYpOsxqt/TPtog8BcUgekAetxQRBErnLZvCTK0xPzdb6g+hv1IB4Fu6Xj7ub3lZf49mWzlniC1LTxV4/IymdfFfIQHCdNyJMurvQ6mWlto=,iv:BpMR+1cohY2FUuP47EYFfDQO6kV1n2oh1S+EZKOFXfg=,tag:pzK4E9CKOOjVUx+D/6fXXQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
