---
apiVersion: v1
kind: Secret
metadata:
  name: pz8-vars
stringData:
  PZ8_IMAGE: ENC[AES256_GCM,data:mz+OyTfBEC582dyvG9lM2s+rZyKmO8eXEtJFo4match8VQ==,iv:vUYyplRESUoEhY7PEj7O04rFIPY+zRhz3LNHqim3Tnw=,tag:VQ2d0nFmoYc2q+cFaLYhZg==,type:str]
  PZ8_TAG: ENC[AES256_GCM,data:OfbXhMqtSeiiskGqxcKSkGBVTlkJ9FpX7nZ0kGmFpP26usm9chDiapMbB7DTd4Iz6K9/2GJTS9+Iox8FfU1xawjCSvXgC21CESCBGlCN,iv:c7A6S4etszXAa90ddzUZyiZtfecsllQF8tmN7dUy1EU=,tag:dFaB7RhfupMehcD9NEYCUg==,type:str]
  PZ8PRX_IMAGE: ENC[AES256_GCM,data:dDUcvN7SfLAFcVKWhPy6qOn7DZbAIwDoube3E0k=,iv:Ln9MiVBf9g8RKMhz3oUOr14/0r14O1djIZ2IO5/b1OY=,tag:n+DmU1oIObs4wzQbQAKWbg==,type:str]
  PZ8PRX_TAG: ENC[AES256_GCM,data:8WdV2UJz+nR7LMTeU/RxveTDvvcNEQ6aMPtHFC7k/CMbEdDrfkVTYMyUd/jMMYdVtwp5ocSDxtRTZsqF6CH9ypBdw5L6otez/cL6+h8y,iv:C9zJI8i+/+110aImTVpNYd4psabDPuW3tRZ/53R9idc=,tag:G/pleHbRwu9bvMEXtS6FBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WnQ5WFJkMnhzMUlRcDAx
        QmN0MWFmUFBCc0tzSnBOSS9pQUh0Y3BtK25FCk5rN04rR1FVV3duRjBMWEFycVFC
        QWd0OEF0cHNiZmdBQWpYR0NPeGR0amMKLS0tIGkxaTdyRVdTaS9NZnNDWHR1R1Ax
        L0ZqdjNoVThoU2U2QXpzUHJENmNrRG8KA/Jh/n+lVgWYg7SuAxJFJmWLTmbWoKJK
        LCnj705nTKS0UX9RWO8+aV4a5NKiamHqJ48HlUm6Y5DhGlbYJxDm0A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-04T19:45:21Z"
  mac: ENC[AES256_GCM,data:n1Q9s9OkwOVfSidZi+WIkxwRDi/sk9X6ccjWXMfCRkKMEHZwqPV4pYaYf0nIXBX52S5sX0noirJWIMZX0eouXNiAxU4H7rVBE7gliJm7cAOfLYM+dQlD9ENcg5cRFghde2nVTJXbqFhw+uDtqT4YZKIvFtj3Eah+kd0hEbP/xmE=,iv:V5+0hLkhVMXq+sTETlv9miW7r937RtBqj6qnBIMhiUg=,tag:7jfQGEZgTgOIIw7iWrwMnA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
