---
# Name is dictated by the chart -- it mounts a Secret called exactly
# "operator-oauth" and the operator pod does not start without it.
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
type: Opaque
stringData:
  client_id: ENC[AES256_GCM,data:+qAHySAwlMTQneHg3d72DTT8BRD0YHt6T7jx3A==,iv:Cor10vrz0NpS0EHwGw/v1LI2eiwbzpGI3t6hpagdpxM=,tag:OO31jzLwV9SSxdx/dVZ5kQ==,type:str]
  client_secret: ENC[AES256_GCM,data:C/DG8W4zXQIY2/7yflc2ohPUI7l3s+J2CKVb/USxHqc=,iv:3Q5ROgTN617pjAZzHR2TfIfbmCxGq8Y5LOeWlsLbv/g=,tag:eO/1Yag5F8H91MJ/RQseyA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK1FQejJETE9ITzdEQTRZ
        UGIwT0l2K3JPWFVSWk4xKzI0VFEzaWNCUGdNCjVFcHhoRVM1U1RLS09MaTJDNDBo
        YlVtcGVhSHJGTVJYWHNpVWtPcDRXRXcKLS0tIGdlQmo1MGxLak1RTlY0TnZaa3FK
        OHV4SEJLM3N5b2dXTzFYTm9rVEtLU2cKi//W1liHNEqOGqsaVCUyLEiGcZy2DdiQ
        Na10HAnVQdkRcmvkFtwpIoUl8nVBAmxfCmTI5aEGmyxx6d+CN7fR5Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T13:28:31Z"
  mac: ENC[AES256_GCM,data:XeRITUGV6hOi6HDo7eUsnev6tatg11TGnSS+MpqkolERa+kSSsthpLriNklR3TQn2FT63W0KgWO14XdcOTzrh0Hc/yJCKibXhPW/o2o8Dh7zRmr4u0JrSi1NNPbeh/Fh+dK7sOm1CXfJyL2HYI3ZxW32CXS71q9/66kncmNlIZE=,iv:h3yPzicK3W+FuoBAyLQsivgJKdtaomRaETd24JhOvp8=,tag:Wco/1vdilWl3j9xQEVOCNw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
