---
# Name is dictated by the chart -- it mounts a Secret called exactly
# "operator-oauth" and the operator pod does not start without it.
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
type: Opaque
stringData:
  client_id: ENC[AES256_GCM,data:lbhUKSLoTazQHkeRYFVJuLQ=,iv:SI5QGaU+vbzvJnMFpkO7b8So7znRlKtZbTvA6xMGK5Q=,tag:qp2JnLUdc80S7f++39VJxA==,type:str]
  client_secret: ENC[AES256_GCM,data:L7v6qGHks7r7AX7fy36Cux277+wpYscWf5F3gmlAXxJK+P0Ul0dpb1IR69kziVwBGOLln/pSx+rADVkzL8Yy,iv:3xVrjXazYX2Lvgaj/llXZXkX6ycrKeX5OfuiwTX1k8w=,tag:uI5CTgyXRM9cw4iDKroD5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK1FQejJETE9ITzdEQTRZ
        UGIwT0l2K3JPWFVSWk4xKzI0VFEzaWNCUGdNCjVFcHhoRVM1U1RLS09MaTJDNDBo
        YlVtcGVhSHJGTVJYWHNpVWtPcDRXRXcKLS0tIGdlQmo1MGxLak1RTlY0TnZaa3FK
        OHV4SEJLM3N5b2dXTzFYTm9rVEtLU2cKi//W1liHNEqOGqsaVCUyLEiGcZy2DdiQ
        Na10HAnVQdkRcmvkFtwpIoUl8nVBAmxfCmTI5aEGmyxx6d+CN7fR5Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T13:44:28Z"
  mac: ENC[AES256_GCM,data:1APbi9vfEm59FBrgF+HS/4r0pIuZeSa4YFcuYxcGDqYWjftml9f8RqLcB0WHHwaLGnS2MScqCmrMb+hvRTFivyFn28T9p4mT7dKpboVNtd+rXVEO9ZdLpOS+gPyGZTC0/jy45d8WSX37YcdDJf/S3sLS8B5e6PADIb2cjmmveIA=,iv:5ye1tODakCAlQ35+ByXGs91aY0W6XPizEVNcvZ1QwP0=,tag:7yfi3IoSdVDnCTKb0uyi9g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
