---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-data
  annotations:
    resize.topolvm.io/storage_limit: 30Gi
    resize.topolvm.io/threshold: 20%
    resize.topolvm.io/increase: 20%
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-meili
  annotations:
    resize.topolvm.io/storage_limit: 15Gi
    resize.topolvm.io/threshold: 20%
    resize.topolvm.io/increase: 20%
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
