---
apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:Pb4cUDEgsYL9BAU4PvQksF3SUhFh7jB4Y9pXJm6s0aEstw==,iv:dDI7Y8tUCj6ghjYpqSkctLbBj0aqQ+qh+nmK9WksFDQ=,tag:AXxjkodW1bmGXTLhoX+AeA==,type:comment]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:7e8XXz3oINyib4gS2xN7CDfdKzQq2hgei/SOulUgZ8URb1neiBQ/WSli736wmEel,iv:SryuijJWXwGEB2Ia0hGgKzvb7l6ZLWuXhZVhPgXVoJk=,tag:zbZ7i0n81RyID99nTfkb0A==,type:str]
  #ENC[AES256_GCM,data:y2FcAdG3jcFqECu0MYgP2Mryd7Nj2t2Q2LXgneKQ2/R3ZiXm1HfwsHAr9J6BZCnLQU9K,iv:o1Mn8M9wj8tQiOgavCkPM7BxtfZz8AgCFULSlZbk7Mc=,tag:+cId0Rijqv3hlbXSiRHzgg==,type:comment]
  MEILI_MASTER_KEY: ENC[AES256_GCM,data:61tZcT6guFXKWwFrJ3hTryiTwi6fX5cZAHOffJyNQb+5xGuVqWE2QQ==,iv:d3WDodN6VDdsplDmRA17QI64eYI1Iepeh+RRsqYzdtE=,tag:XhqLruMAhmbKHlI9qhAkJw==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:crbJxlRd91c9a9I6uBhw7yQgQ4HuQma5Nk5+mb6XSZTfAecIJbiBGsm5gf/bwMfrB3NbJqZIdjR1JiEPKs5+lw==,iv:HPTpTf3mOPQLncPOSFDEevoryCErDR903k+9zrqJQyU=,tag:/VughoM9nCspiJpJA/vF3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZnpZaVNZQk5TM25GcStU
        UUEvL0grMGFSR3M2WnlRWmp0Y0Mwa01RVGlFCnc2eTBqR20wTTYxYTNHNEFhQ1dL
        NkdLRklmeHFiR0FScmhtaVdIOWJXTUUKLS0tIE1sVzdlSyt3RzdLeVJCMjB1am1q
        OTNTL2FuNTNFSUxkK002SUZqYzJmdjgKRp1pSFSLrNsyVVGS/GIuTVPiO9938iSC
        F2Br41rY/AD2d/wrWciFWY7nzTwpLMpf1h5vfCiSzetBMiLgLRK4oA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T20:54:49Z"
  mac: ENC[AES256_GCM,data:Ofcxb/SZus/nxrAa+M4cWYAnRrvA46vTA8CXHS8dJJbzXSFp8o0MZ3EKADCoWosnBrEoKn2vgWyMmm7nL9NstLaM1pZI2poLGajhPyiEvt5fCyFW7XPFfqRP2aFueSk2i9bUk6JMh3ifdXcBeAcIbv4Awd3b1lwsncNcqqNth4g=,iv:ADGwZr7/onQaINc+o5t+kbOdiwi9AY8mBCGcZrG3tz8=,tag:vTt/fXAWX7Hkb3QVdhGCNg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
