---
apiVersion: v1
kind: Secret
metadata:
  name: dawarich-secret
stringData:
  #ENC[AES256_GCM,data:/0s3GFudLw2uN7NV3l0ATiqgUphT8zfZ+fwAHH6LyYWI3vfVRAisePG2+sTD36Sr0MS83n3Eo5z345o=,iv:cqU4pl+NkVIok7QebozMhSKcw89N1f/5Qm0S4pnqKUw=,tag:r/4Y7WC1mU1+zbDDuaSavg==,type:comment]
  #ENC[AES256_GCM,data:8qyVLCraRY7Q4WFv8YY62EAikBsZNgcIO+5vVZsD9D0S9uLMCXgOp33HZC5LbfwuEjs14lYLEcYT3+bcvwSwu8BDoud/aDVk,iv:xS4lsPBLK/WaRbePheZySlTMP/vBmwRD8Yx4CM7jQQM=,tag:ZVq3MF1JwtI1/mDZ5CvZww==,type:comment]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:RSYOwVCszKJOV0Fc2laSj4BRNSW+TrcT1wIS5e47xPFtIPFq62W+fKIskZ0Xc+msvn0yGwSQG4+t+EMlfJBi0egKBk/HdZVVCC7755/uevnKWuKTkT3b4YGQy4RXG2bsWyQHMayzpRg087kj2JclSd9MasFxdnx2+ydSdQSNm0Q=,iv:WUbcqhyAkh8FHkgnKR14EoC9KkDSAZKZtklqAEpTBhE=,tag:j86vhMZNXcxsaqeEzBYE3w==,type:str]
  #ENC[AES256_GCM,data:tOtVabIAuPwahdhW+idPb4nFS42QDoPlZ9BAZTyMT6o/NMCW/HokOBg+ENI83STnRi/5XKpo4g==,iv:UmxXfn8P+DYAFmb5iVJ3/KfulgQm3b/jtzmH0czCXdw=,tag:9dcE6Oe+PXSxzKLaHfLGCw==,type:comment]
  #
  #ENC[AES256_GCM,data:UI41evKu0ACCgkbLJcNBqv2yq1cCsf2sOaHo6ghCIUbgwOsieG+kHemH0f9Z2EwT7hJoQAYp55bd71rC+uLuwHW7mKBZmvkAr9I=,iv:EtLT0c8Wdsu/5bKWV72o5JMr6lmeQOD0fcKDIM+6IJM=,tag:x1ITOsj0K7CdHuyDyE1Pkw==,type:comment]
  #ENC[AES256_GCM,data:O0aWgam0bM0Dais5wNHmnUC0B8XDdg55r/2V3j25FXSc1ZHSfz7CzRXub85v6/T3oYasbqv9DTwWkJ5jjTd+qFWu28TploqV,iv:Kto0YJfYLura+9u6IoqoAQZyXh8p9r3DdbzDWqmJwRA=,tag:+LW0hLT5oQp5WnwNWL+cZg==,type:comment]
  #ENC[AES256_GCM,data:lVAR+uAW9Hl0LhqNSJ+KqEJlsHEcJgoHURK+S0493lDM3Uv69JwNN6GywfzL50rgcZHjyPTfWik6MLSP/v4EP6GnO8YBoMBWpQ==,iv:3sH5WGauR0vQew9x35tYUFHsR+vBdKw+ta4PALUyJGc=,tag:2lGL4OewF/Fr5fQUJKvZvQ==,type:comment]
  #ENC[AES256_GCM,data:0wYwQ1MLxF+fZBDdmikJeCWtyRnbe41TXAwhYtkeKNwaYfayvYHQjaM8pLprHiw4sokZOHvbhoABssHZ1cYhaT7hCD2kBAfi,iv:zkxP6498LIvR2DTXxUy/auCJqbhHE+0orb0wZGJ/Ack=,tag:8xlzoxOVP/yN9VRkgNrIWw==,type:comment]
  #ENC[AES256_GCM,data:K+u+Dj8IOxt6FugTBHBM2AgicMqYLYBuRGsiY4/DVijeAy/gobIGaW5ivEt8CTKrLHqbldYEJ8zs6218nZRBZ16Gss8=,iv:K3QwmkXsRWxOmvsc4oanIJi6WSMRyPmE7dzEUAEt94I=,tag:TtQa+0fIdC6vKTlYoEKmcA==,type:comment]
  #ENC[AES256_GCM,data:F6OcnTGASAuQAoTsdka4f+6Z9ZwjEiG7pC0qh//dXBii8QsrmFd2mX/X180=,iv:4ycpOqKO2OLeYeAbLKqnknqUXZOzig3VqRSqWOmCnms=,tag:QR2JNQTBs96/iB40PK5aWQ==,type:comment]
  PHOTON_API_KEY: ENC[AES256_GCM,data:FIsgWjvesPI33nF8jBRcxmXwhLFSmU89YpPdScRx63iNOt0=,iv:2obPlpQlIfnLR2MpJTTtFGKfl0HWs2zHBQsvtZUriYQ=,tag:ODgOI4K0NapiHIMkBl1Txw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYnA1QnU4eEJXZ1ptWVFo
        bCt4dVRtMHA3aDlibFBtSGFRTkZkdWk0NERZClM1RWQyQ3BzYml1S1NIaFRPenYw
        ZmxGMjNtSVBRNTJXQmlUYWRiaTFqdWcKLS0tIEQwUXBYcXY1MWxDVE9ldWpYem9l
        UnJ5WG1KZXdXWTV6S2VOS1dKdFNtencKi38+qUTofS0tu/vyeOr4DjAzFqLJ3skh
        zleA5KZT7sQ91bXW5ERKVPb12EsYYwjD7zYx3w+14ov0gf3nSFXneQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T11:49:00Z"
  mac: ENC[AES256_GCM,data:Y9WROgNfTR289aA7R6wzNCxf7Yw7Py32DJW/H2VgbzmFjzO1ePOXqcAxSfdANolD1ImBaE/FInrRTuVQCn2TrJJqKjbbszP/4E5Eh7rdQi41vZNOZjWooW++LgHYz+Axua//gSIeAkANlVYDb40h0gM/nfovg+Ijy889jqVOCyc=,iv:Vnlt0Rj/AVnCDc7KqeLJhqT254HthvCLgmJHdGi6uCs=,tag:sSbrLd9mj7fFGOOUc4cc/g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
