# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/persistentvolumeclaim_v1.json
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  annotations:
    resize.topolvm.io/storage_limit: 10Gi
    resize.topolvm.io/threshold: 20%
    resize.topolvm.io/increase: 20%
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
