---
apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:33Hv+E/zswrjgFk/dMN1HJTBOBDtAkLV4TFWNmL2HjwLIxZn1HV3iYUdB40lo3RAH+ZCfodwQx5epljj9kT5pwYtEipG72E=,iv:iLw3Zyij4wDetxl2Nn/odEnUeZ96T8R8gtazYZtTJVo=,tag:kXFloeeqKDn72t9PhlU5Lg==,type:comment]
  #ENC[AES256_GCM,data:zHD4M7POsq0AK0mXQ7srxspuL9+bBbYeGoGpqUALqNhtZV+U,iv:alrM6tyN9ZctLqWMskbuMBQ/axqXqAGAsa5RAf0758I=,tag:AdcRZLcqjzXiePpB/KwXzg==,type:comment]
  ENCRYPTION_KEY: ENC[AES256_GCM,data:MZjSws7jxm5fwDkQJAt9LGWjs7qc2rnFL7NVtdoczlTPXplaJ/sJwrq4jTk=,iv:Cf+8DV0yX58HUjnkEEMCjzoDCZzX7Iheb3R5wPa2/WI=,tag:Brj0r6NpkMZ2uI/tbtx3LQ==,type:str]
  #ENC[AES256_GCM,data:Evqd9JGF7p7C0V+NdMrNUfmLvihKvOnd9Q==,iv:rB+xwC3bGRkLU1SV/HMKo/JMwXt9Dh83ams4+ekdOsY=,tag:dogNyDWvQuPBlzVgkHzPPQ==,type:comment]
  #ENC[AES256_GCM,data:5BRykLTMJAwCj/RxWl5T6xdoc8fuYx7VKxnYdyrrvQt09EFe9MVDe7Ht8uLDOGDMKSSEMGlrs32eo/D8SvU0,iv:F3PFecAjqA3naIEBi2QAWZr6W860nRDqE5MFVHLbOx0=,tag:py/aVy+J3eq5Yumn4AB+vA==,type:comment]
  SMTP_HOST: ENC[AES256_GCM,data:I5VWYuDPKV4w0hKW2puS1Q==,iv:/KuCEkowQE/EBv/fBd91Cx0E7R3aswBHgE7PfSb/iSo=,tag:14kCMYw0g5Y4XSRK9Fz/Cg==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:5zu8,iv:avzfyTf37y35Si3p2uXq6Ew7DZGXJZSvQ9eZsNVbVnI=,tag:YZbtbz6i3iG55DwuLB7x7w==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:RhhY1uQem/TWE1GslqY=,iv:sd8ftQpfQZrqLGAV9ggI9ZWlcv5UHjoUutYsDbo6r2E=,tag:XBwh5zQx4wGpKLwGYaYwPg==,type:str]
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  SMTP_TLS: ENC[AES256_GCM,data:hfeiQw+zePs=,iv:QNzVez1vF0aA9wyaevwUDtho7QpCadgUy10Fm0f7o9g=,tag:BktwGOOIe+ePgIy5S1dUDw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZEo4UFFGeVdrbWtuenFN
        bDA2ZmhFWElMMUdINnVpNUpua3dZQlNWbTI4CllZeC9TOFNiTmJpbk92VU5URldD
        eURMaUYyMURVT3IxTldzZDV0TEVKZXcKLS0tIFJVT1ZiK0ZCQWNYTjZWYTh6UjB2
        b3VYNXphc2V2dWxjTU9sU2FUUWN0d0UKmgMYTHsA/AxVGvfsRiQ0XFT8bIS3/x4C
        z9hnAlCMjbGNlzYuXsmTDHhlrsMPiH703xJuuLKa5MJTMbyt1MXfdA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-24T21:35:36Z"
  mac: ENC[AES256_GCM,data:BraIzaMldNFcaMv8Re90AC6HCKew8485B/kjvUbs0OAbW0PyBcH+Sapoxp+lFbCD42g8By146wjav0rYtNT9faALaqUi1nNpoWgnRuIRbf2ddXXyjSoWLG/KNa8pXXNikRR2xArDhrNmt2zN90S1m2NGDHg9o9GNOjSfFKvhMpk=,iv:XGSIyQeYi5uRDf9FEnwAxwjoQVcDFhFoJT8biOkrMjA=,tag:a/AALSamGBgzWoQT39r/5g==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
