---
apiVersion: v1
kind: Secret
metadata:
  name: rtabby-users
stringData:
  #ENC[AES256_GCM,data:wajB+fWIt/aDs0cN+L7nLk8YSqzvh4xr6q8ZoVOJAwub5fzh122b67GVT1RVWmsmO8g4RDoPdGlGOK8wmxT4Bb0HuOZIj5Zlpg==,iv:ysWI9qF1LA3J3mafXWyqaJU25zCTE06sSbmU+I+sG1s=,tag:eyRAoSozbgtLTYnThDRdug==,type:comment]
  #ENC[AES256_GCM,data:Wz0O2Nuyf/hijK2T3/7yv7aX4liwkSjdpf3Eu2e06yb7e4wDyhDheOyF5S+6pxL2bB60CTWlOt+JFcIO7rlXyuY9iGOUaFe6YQ==,iv:mJaJI2B0P7lSlxsWmBfCh6b6eEU0uhoalU+wjwLO8mU=,tag:8LuXutvwWGZ2Nf1yt62Ncw==,type:comment]
  users.yml: ENC[AES256_GCM,data:s++UjUdW/rZiSIL52BajQNCcpPRwdSRbKLLEVPm8smP51FZxay8zBK9xMcqIjTbHqXNujOV3kHfwhAIenZJ6vvE/8Zz7oi5kJARi,iv:HXa9Q/YmLhUGneWd5/9HsmM05WOpVCnPiPC01Yyd/lM=,tag:27vVKuzXOh9hclZbS5lXzw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYXBidEdtMjk0QVlrUHIr
        UTdpYTg3cGMwWlJVQmpxMDZ2ZU5oMGdXMTFBCkk1ejREaGovOEprT01GNFU5d00z
        djZKT2tOLzN2VEJ3TUxNYXpiQmlIUjAKLS0tIHhTNmZIamlFd3I0bzB5aXdBT05E
        OXZYaklCS1JNaUZkR1ZTcUJlUEwxREUK2wiOWHG+KoVHhkNXtaIbYbLvuisEwk1j
        61qRiYN5VldgT5+fOFfN1q+oFSQyj2/WbIFMtE3xsRezz2BdB6zZgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1txcyeza70lxefaz3m45jxyf074czteej3z843js7z9fh8ndv5pxqll2tex
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T18:41:45Z"
  mac: ENC[AES256_GCM,data:JjYiuU+HH03HWkiMtGcu1Ofk2FurkjJaFQ7yitOmPX45sz/FF44N5wtzqoli4mN/MzU+Oiq8q9LZYRDLbtcS2xX0Uyd0WclXsvE/i7UrUJgoTiD/nwqlFaWKF8esex/Vsgt+xiXGab1mQqTZUAso702CL3TShlEt+jxFsssVGj4=,iv:ERXxdY3SIOqFve/hd0cOI5FMTrTOAtIw2GoWbCiV7+E=,tag:1mP6AL9qI+8L6xz/bpaYDQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
