---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trilium
spec:
  interval: 1h
  path: ./kubernetes/apps/trilium/trilium/app
  postBuild:
    substitute:
      APP: trilium
      VOLSYNC_CLAIM: trilium-data
      VOLSYNC_SCHEDULE: "0 5 * * *"
      VOLSYNC_CACHE_CAPACITY: 2Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: trilium
  wait: false
